name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Use Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Install Tweego
        run: |
          wget -O tweego.zip https://github.com/tmedwards/tweego/releases/download/v2.1.1/tweego-2.1.1-linux-x64.zip
          unzip tweego.zip
          chmod +x tweego
          sudo mv tweego /usr/local/bin/

      - name: Build game
        run: |
          tweego src -o dist/index.html --module=env-prod.js

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./dist

      - name: Deploy to Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./src/images
          destination_dir: src/images
          keep_files: true